/*
 * 2024 Tarpeeksi Hyvae Soft
 * 
 */

export default {
    info: Rngon.texture({
        "width": 13,
        "height": 12,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAD/6QD//+kA///pAP//6QD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/6QD/AAAA/wAAAP8AAAD/AAAA///pAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+kA/wAAAP8AAAD/AAAA/wAAAP//6QD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/pAP//6QD//+kA///pAP//6QD//+kA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/pAP8AAAD/AAAA/wAAAP8AAAD/AAAA///pAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+kA/wAAAP8AAAD/AAAA/wAAAP//6QD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/pAP8AAAD/AAAA/wAAAP8AAAD//+kA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/6QD/AAAA/wAAAP8AAAD/AAAA///pAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+kA/wAAAP8AAAD/AAAA/wAAAP//6QD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+kA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA///pAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/6QD//+kA///pAP//6QD//+kA///pAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    trash: Rngon.texture({
        "width": 13,
        "height": 13,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP//AAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP//AAD9/wAA/f8AAP3/AAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA/f8AAP3/AAD9/wAA/f8AAP0AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP0AAAD//wAA/QAAAP//AAD9AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD9AAAA//8AAP0AAAD//wAA/QAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA/QAAAP//AAD9AAAA//8AAP0AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP0AAAD//wAA/QAAAP//AAD9AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD9AAAA//8AAP0AAAD//wAA/QAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    clipboard: Rngon.texture({
        "width": 12,
        "height": 12,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD//////wAAAP8AAAD/AAAA/wAAAP//////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD//////wAAAP8AAAD/AAAA/wAAAP//////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD//////wAAAP8AAAD/AAAA/wAAAP//////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    wait: Rngon.texture({
        "width": 19,
        "height": 19,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsvxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/wAAAAAAAAAALL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAAAAAAAACy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAD/AAAA/yy/FP8svxT/LL8U/yy/FP8svxT/AAAAAAAAAAAsvxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAD//v7+/AAAAP8svxT/LL8U/yy/FP8svxT/LL8U/wAAAAAAAAAALL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAD//v7+/AAAAP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAAAAAAAACy/FP8svxT/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD//v7+/P7+/vwAAAD/AAAA/wAAAP8AAAD/LL8U/yy/FP8svxT/AAAAAAAAAAAsvxT/AAAA/wAAAP/+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78AAAA/wAAAP8svxT/LL8U/wAAAAAAAAAALL8U/wAAAP/+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vwAAAD/LL8U/yy/FP8AAAAAAAAAACy/FP8AAAD//v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78AAAA/yy/FP8svxT/AAAAAAAAAAAsvxT/AAAA//7+/vwAAAD/AAAA//7+/vz+/v78AAAA/wAAAP/+/v78/v7+/AAAAP8AAAD//v7+/AAAAP8svxT/LL8U/wAAAAAAAAAALL8U/wAAAP/+/v78AAAA/wAAAP/+/v78/v7+/AAAAP8AAAD//v7+/P7+/vwAAAD/AAAA//7+/vwAAAD/LL8U/yy/FP8AAAAAAAAAACy/FP8AAAD//v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78AAAA/yy/FP8svxT/AAAAAAAAAAAsvxT/AAAA//7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/AAAAP8svxT/LL8U/wAAAAAAAAAALL8U/wAAAP8AAAD//v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/AAAAP8AAAD/LL8U/yy/FP8AAAAAAAAAACy/FP8svxT/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/LL8U/yy/FP8svxT/AAAAAAAAAAAsvxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/wAAAAAAAAAALL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    edit: Rngon.texture({
        "width": 13,
        "height": 13,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/QAA//0AAP8AAAAA/QAA//0AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//gAA/wAAAAAAAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAD//gAA/wAAAAD+AAD//gAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    clear: Rngon.texture({
        "width": 13,
        "height": 13,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAP//GRn//xkZ//8ZGf//GRn//xkZ//8ZGf//GRn/AAAA/wAAAAAAAAAAAAAAAAAAAP//GRn//xkZ//8ZGf8AAAD//xkZ/wAAAP//AAD//xkZ/wAAAP8AAAAAAAAAAAAAAP//GRn//xkZ//8ZGf//GRn//xkZ/wAAAP//GRn//wAA//8ZGf8AAAD/AAAAAAAAAAAAAAAAAAAA//8ZGf//GRn//xkZ/wAAAP//GRn/AAAA//8AAP//GRn/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD//xkZ//8ZGf//GRn//xkZ//8ZGf//GRn//xkZ/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
};
