/*
 * 2024 Tarpeeksi Hyvae Soft
 * 
 */

export default {
    info: Rngon.texture({
        "width": 12,
        "height": 12,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAP8AAAD///AA///wAP//8AD///AA///wAP//8AD/AAAA/wAAAP8AAAAAAAAAAAAAAP//8AD///AA///wAP8AAAD/AAAA///wAP//8AD///AA/wAAAP8AAAAAAAAAAAAAAP//8AD///AA///wAP//8AD///AA///wAP//8AD///AA/wAAAP8AAAAAAAAAAAAAAP//8AD///AA///wAP8AAAD/AAAA///wAP//8AD///AA/wAAAP8AAAAAAAAAAAAAAP//8AD///AA///wAP8AAAD/AAAA///wAP//8AD///AA/wAAAP8AAAAAAAAAAAAAAP//8AD///AA///wAP8AAAD/AAAA///wAP//8AD///AA/wAAAP8AAAAAAAAAAAAAAP//8AD///AA/wAAAP8AAAD/AAAA/wAAAP//8AD///AA/wAAAP8AAAAAAAAAAAAAAP8AAAD///AA///wAP//8AD///AA///wAP//8AD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    trash: Rngon.texture({
        "width": 13,
        "height": 13,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP//AAD9/wAA/f8AAP0AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA/f8AAP3/AAD9/wAA/f8AAP0AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP0AAAD//wAA/QAAAP//AAD9AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD9AAAA//8AAP0AAAD//wAA/QAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA/QAAAP//AAD9AAAA//8AAP0AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP0AAAD//wAA/QAAAP//AAD9AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD9AAAA//8AAP0AAAD//wAA/QAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    clipboard: Rngon.texture({
        "width": 12,
        "height": 12,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////8AAAD/AAAA////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD//////wAAAP8AAAD//////wAAAP//////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD//////wAAAP8AAAD/AAAA/wAAAP//////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD//////wAAAP//////AAAA/wAAAP//////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    wait: Rngon.texture({
        "width": 19,
        "height": 19,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsvxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/wAAAAAAAAAALL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAAAAAAAACy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAD/AAAA/yy/FP8svxT/LL8U/yy/FP8svxT/AAAAAAAAAAAsvxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAD//v7+/AAAAP8svxT/LL8U/yy/FP8svxT/LL8U/wAAAAAAAAAALL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAD//v7+/AAAAP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAAAAAAAACy/FP8svxT/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD//v7+/P7+/vwAAAD/AAAA/wAAAP8AAAD/LL8U/yy/FP8svxT/AAAAAAAAAAAsvxT/AAAA/wAAAP/+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78AAAA/wAAAP8svxT/LL8U/wAAAAAAAAAALL8U/wAAAP/+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vwAAAD/LL8U/yy/FP8AAAAAAAAAACy/FP8AAAD//v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78AAAA/yy/FP8svxT/AAAAAAAAAAAsvxT/AAAA//7+/vwAAAD/AAAA//7+/vz+/v78AAAA/wAAAP/+/v78/v7+/AAAAP8AAAD//v7+/AAAAP8svxT/LL8U/wAAAAAAAAAALL8U/wAAAP/+/v78AAAA/wAAAP/+/v78/v7+/AAAAP8AAAD//v7+/P7+/vwAAAD/AAAA//7+/vwAAAD/LL8U/yy/FP8AAAAAAAAAACy/FP8AAAD//v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78AAAA/yy/FP8svxT/AAAAAAAAAAAsvxT/AAAA//7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/AAAAP8svxT/LL8U/wAAAAAAAAAALL8U/wAAAP8AAAD//v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/P7+/vz+/v78/v7+/AAAAP8AAAD/LL8U/yy/FP8AAAAAAAAAACy/FP8svxT/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/LL8U/yy/FP8svxT/AAAAAAAAAAAsvxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/wAAAAAAAAAALL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8svxT/LL8U/yy/FP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    editMessage: Rngon.texture({
        "width": 13,
        "height": 13,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAAAAAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAAAAAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
    clear: Rngon.texture({
        "width": 13,
        "height": 13,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAP/////8/////P////z////8/////P////z/////AAAA/wAAAAAAAAAAAAAAAAAAAP/////8/////P////z/////AAAA//////8AAAD//////wAAAP8AAAAAAAAAAAAAAP/////8/////P////z////8//////////8AAAD//////P////8AAAD/AAAAAAAAAAAAAAAAAAAA//////z////8//////////8AAAD//////wAAAP//////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAD//////P////z////8/////P////z////8/////wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "rgba:8+8+8+8"
    }),
};
