export const icons = {
    app16: Rngon.texture({
        width:16,
        height:16,
        encoding:"base64",
        channels:"rgba:8+8+8+8",
        pixels:"AAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AgAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wCAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP///wD/AAAA/wD///8A////AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wD///8A////AP///wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/AwMD//////8DAwP8AAAD/AAAA/wAAAP8A////AP///wD///8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////4CAgP/AwMD/////////////////AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////////////+AgID//////////////////////wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////gICA//////8AAAD/AAAA////////////gICA//////8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////8AAAD//wAA/wAAAP8AAAD/////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD//wAA/wAAAP8AAAD/wMDA/8DAwP+AgID//////wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD///////////8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAA=="
    }),
    app32: Rngon.texture({
        width:32,
        height:32,
        channels:"rgba:8+8+8+8",
        encoding:"base64",
        pixels:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wCAAP8AgAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AAAA/wCAAP8AgAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AAAA/wCAAP8AgAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AAAA/wCAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wD///8A////AP///wD///8A/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AP///wD/AAAA/4CAAP+AgAD/gIAA/4CAAP+AgAD/AAAA/wD///8A////AP///wD///8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A/wAAAP+AgAD/gIAA/4CAAP+AgAD/gIAA/wAAAP/AwMD/AAAA/wAAAP8AAAD/AAAA/wD///8A////AP///wD///8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/gIAA/4CAAP+AgAD/gIAA/4CAAP8AAAD/wMDA///////AwMD/wMDA/8DAwP/AwMD/AAAA/wAAAP8AAAD/AAAA/wD///8A////AP///wD///8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/4CAgP///////////8DAwP/AwMD/wMDA/8DAwP/AwMD/wMDA/8DAwP/AwMD/AAAA/wAAAP8AAAD/AAAA/wD///8A////AP///wD///8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/AwMD////////////AwMD/wMDA/4CAgP/AwMD/wMDA///////////////////////AwMD/wMDA/8DAwP/AwMD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////////////AwMD/wMDA/8DAwP///////////4CAgP/////////////////////////////////AwMD/wMDA/8DAwP/AwMD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////4CAgP///////////////////////////////////////////////////////////4CAgP////////////////////////////////8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////////4CAgP///////////////////////////////////////////////////////////4CAgP///////////wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////gICA////////////////////////////////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////4CAgP////////////////////////////////8AAAD/AAAA/8DAwP///////////4CAgP////////////////////////////////8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////////4CAgP/AwMD/AAAA//8A////AP//AAAA/8DAwP///////////////////////////4CAgP///////////wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////wMDA/wAAAP//AP///wD//wAAAP+AAID/AAAA////////////////////////////////////////////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////4CAgP////////////////8AAAD//wD///8A//8AAAD/gACA/4AAgP8AAAD//////4CAgP////////////////////////////////8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////////wAAAP//AP//AAAA/4AAgP+AAID/gACA/wAAAP///////////8DAwP/AwMD//////4CAgP///////////wAAAP+AgID/gICA/4CAgP+AgID/gICA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////AAAA//8A//8AAAD/gACA/4AAgP+AAID/AAAA///////AwMD/wMDA/8DAwP/AwMD/////////////////AAAA/4CAgP+AgID/gICA/4CAgP+AgID/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD///////////8AAAD//wD//wAAAP+AAID/gACA/4AAgP8AAAD/wMDA/8DAwP/AwMD/wMDA/8DAwP/AwMD///////////8AAAD/gICA/4CAgP+AgID/gICA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP//AP//AAAA/4AAgP+AAID/AAAA/8DAwP/AwMD/wMDA/8DAwP/AwMD/wMDA/4CAgP///////////wAAAP+AgID/gICA/4CAgP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/gACA/wAAAP8AAAD/AAAA/8DAwP/AwMD/wMDA/8DAwP//////////////////////AAAA/4CAgP+AgID/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA//////////////////////8AAAD/gICA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    }),
    0: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAABAQEBAQEAAAEAAAEBAQEAAAEBAQAAAAAAAAEBAQEAAAAAAAABAQEBAAAAAAAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQEBAAAAAAAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQEBAAAAAAAAAQEBAAABAQEBAAABAAABAQEBAQEAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    1: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAABAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    2: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAABAQEBAQEAAAAAAAEBAQEAAAEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAEBAQEAAAEAAAEBAQEBAQAAAQAAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAAABAQEBAAAAAAABAQEBAQEAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    3: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAABAQEBAQEAAAAAAAEBAQEAAAEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAEBAQEAAAEAAAEBAQEBAQAAAAAAAAAAAAAAAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAABAQEBAAABAAABAQEBAQEAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    4: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAAAAAAAAAAAAAEAAAAAAAAAAAEBAQAAAAAAAAEBAQEAAAAAAAABAQEBAAAAAAAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQEAAAEBAQEAAAEAAAEBAQEBAQAAAAAAAAAAAAAAAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAABAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    5: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAABAQEBAQEAAAEAAAEBAQEAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEAAAEBAQEAAAAAAAEBAQEBAQAAAAAAAAAAAAAAAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAABAQEBAAABAAABAQEBAQEAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    6: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAABAQEBAQEAAAEAAAEBAQEAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEAAAEBAQEAAAAAAAEBAQEBAQAAAQAAAAAAAAAAAQEBAAAAAAAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQEBAAAAAAAAAQEBAAABAQEBAAABAAABAQEBAQEAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    7: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAABAQEBAQEAAAAAAAEBAQEAAAEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAABAAAAAAAAAAAAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    8: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAABAQEBAQEAAAEAAAEBAQEAAAEBAQAAAAAAAAEBAQEAAAAAAAABAQEBAAAAAAAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQEAAAEBAQEAAAEAAAEBAQEBAQAAAQAAAAAAAAAAAQEBAAAAAAAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQEBAAAAAAAAAQEBAAABAQEBAAABAAABAQEBAQEAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
    9: Rngon.texture({
        "width": 10,
        "height": 16,
        "pixels": "AAABAQEBAQEAAAEAAAEBAQEAAAEBAQAAAAAAAAEBAQEAAAAAAAABAQEBAAAAAAAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQEAAAEBAQEAAAEAAAEBAQEBAQAAAAAAAAAAAAAAAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAABAQEBAAABAAABAQEBAQEAAA==",
        "encoding": "base64",
        "channels": "binary"
    }),
};
